### PR TITLE
cheminfo build

### PR DESCRIPTION
**Pull request by stropitek**
@targos 

Can you make a quick review?

### CODE REVIEW

**Comment by targos** [comment]
Can you separate the rollup build and the cheminfo build, i.e. rollup in a different command?

**Comment by stropitek** [comment]
Yes I can do that. But `npm run build` should do the cheminfo build right? otherwise it would not work with grm.

Also because of es modules, the build is awkward to use: `arrayXY.mergeCentroids.default()`

Can I just `module.exports = {mergeCentroids: mergeCentroids.default}` ?

**Comment by targos** [comment]
Yes and yes

**Comment by targos** [comment]
Wait there is something wrong

**Comment by targos** [comment]
By default rollup does not export like this when there is only one default export

**Comment by targos** [comment]
implemented in https://github.com/cheminfo-js/array-xy/commit/65d8a52457b5b27361dec7049bfc6cf1762bc931

The trick was to use the ESM source instead of the rolled up one.

**Pull request closed without merging**
